/**
 * This class is generated by jOOQ
 */
package jooqdb;


import javax.annotation.Generated;

import jooqdb.tables.Event;
import jooqdb.tables.EventAttendees;
import jooqdb.tables.FriendRequestStash;
import jooqdb.tables.User;
import jooqdb.tables.UserFriends;


/**
 * Convenience access to all tables in SMRTMS
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table SMRTMS.Event
	 */
	public static final Event EVENT = jooqdb.tables.Event.EVENT;

	/**
	 * The table SMRTMS.Event_Attendees
	 */
	public static final EventAttendees EVENT_ATTENDEES = jooqdb.tables.EventAttendees.EVENT_ATTENDEES;

	/**
	 * The table SMRTMS.Friend_Request_Stash
	 */
	public static final FriendRequestStash FRIEND_REQUEST_STASH = jooqdb.tables.FriendRequestStash.FRIEND_REQUEST_STASH;

	/**
	 * The table SMRTMS.User
	 */
	public static final User USER = jooqdb.tables.User.USER;

	/**
	 * The table SMRTMS.User_Friends
	 */
	public static final UserFriends USER_FRIENDS = jooqdb.tables.UserFriends.USER_FRIENDS;
}
