/**
 * This class is generated by jOOQ
 */
package jooqdb.tables;


import javax.annotation.Generated;

import jooqdb.Smrtms;
import jooqdb.tables.records.EventAttendeesRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventAttendees extends TableImpl<EventAttendeesRecord> {

	private static final long serialVersionUID = -1691269233;

	/**
	 * The reference instance of <code>SMRTMS.Event_Attendees</code>
	 */
	public static final EventAttendees EVENT_ATTENDEES = new EventAttendees();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EventAttendeesRecord> getRecordType() {
		return EventAttendeesRecord.class;
	}

	/**
	 * The column <code>SMRTMS.Event_Attendees.User_ID</code>.
	 */
	public final TableField<EventAttendeesRecord, Integer> USER_ID = createField("User_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>SMRTMS.Event_Attendees.Event_ID</code>.
	 */
	public final TableField<EventAttendeesRecord, Integer> EVENT_ID = createField("Event_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>SMRTMS.Event_Attendees</code> table reference
	 */
	public EventAttendees() {
		this("Event_Attendees", null);
	}

	/**
	 * Create an aliased <code>SMRTMS.Event_Attendees</code> table reference
	 */
	public EventAttendees(String alias) {
		this(alias, EVENT_ATTENDEES);
	}

	private EventAttendees(String alias, Table<EventAttendeesRecord> aliased) {
		this(alias, aliased, null);
	}

	private EventAttendees(String alias, Table<EventAttendeesRecord> aliased, Field<?>[] parameters) {
		super(alias, Smrtms.SMRTMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventAttendees as(String alias) {
		return new EventAttendees(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EventAttendees rename(String name) {
		return new EventAttendees(name, null);
	}
}
