/**
 * This class is generated by jOOQ
 */
package jooqdb;


import javax.annotation.Generated;

import jooqdb.tables.Event;
import jooqdb.tables.User;
import jooqdb.tables.records.EventRecord;
import jooqdb.tables.records.UserRecord;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>SMRTMS</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<EventRecord> KEY_EVENT_ID = UniqueKeys0.KEY_EVENT_ID;
	public static final UniqueKey<UserRecord> KEY_USER_ID = UniqueKeys0.KEY_USER_ID;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<EventRecord> KEY_EVENT_ID = createUniqueKey(Event.EVENT, Event.EVENT.ID);
		public static final UniqueKey<UserRecord> KEY_USER_ID = createUniqueKey(User.USER, User.USER.ID);
	}
}
