/**
 * This class is generated by jOOQ
 */
package jooqdb;


import javax.annotation.Generated;

import jooqdb.tables.Author;


/**
 * Convenience access to all tables in library
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table library.author
	 */
	public static final Author AUTHOR = jooqdb.tables.Author.AUTHOR;
}
