/**
 * This class is generated by jOOQ
 */
package jooqdb.tables.records;


import javax.annotation.Generated;

import jooqdb.tables.UserFriends;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFriendsRecord extends TableRecordImpl<UserFriendsRecord> implements Record3<String, String, Byte> {

	private static final long serialVersionUID = -1598265010;

	/**
	 * Setter for <code>SMRTMS.User_Friends.Friender_ID</code>.
	 */
	public void setFrienderId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>SMRTMS.User_Friends.Friender_ID</code>.
	 */
	public String getFrienderId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>SMRTMS.User_Friends.Friendee_ID</code>.
	 */
	public void setFriendeeId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>SMRTMS.User_Friends.Friendee_ID</code>.
	 */
	public String getFriendeeId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>SMRTMS.User_Friends.Tracking_Flag</code>.
	 */
	public void setTrackingFlag(Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>SMRTMS.User_Friends.Tracking_Flag</code>.
	 */
	public Byte getTrackingFlag() {
		return (Byte) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, Byte> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, Byte> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return UserFriends.USER_FRIENDS.FRIENDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return UserFriends.USER_FRIENDS.FRIENDEE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field3() {
		return UserFriends.USER_FRIENDS.TRACKING_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getFrienderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFriendeeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value3() {
		return getTrackingFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFriendsRecord value1(String value) {
		setFrienderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFriendsRecord value2(String value) {
		setFriendeeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFriendsRecord value3(Byte value) {
		setTrackingFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFriendsRecord values(String value1, String value2, Byte value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserFriendsRecord
	 */
	public UserFriendsRecord() {
		super(UserFriends.USER_FRIENDS);
	}

	/**
	 * Create a detached, initialised UserFriendsRecord
	 */
	public UserFriendsRecord(String frienderId, String friendeeId, Byte trackingFlag) {
		super(UserFriends.USER_FRIENDS);

		setValue(0, frienderId);
		setValue(1, friendeeId);
		setValue(2, trackingFlag);
	}
}
