/**
 * This class is generated by jOOQ
 */
package jooqdb.tables.records;


import javax.annotation.Generated;

import jooqdb.tables.EventAttendees;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventAttendeesRecord extends TableRecordImpl<EventAttendeesRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = -1965813876;

	/**
	 * Setter for <code>SMRTMS.Event_Attendees.User_ID</code>.
	 */
	public void setUserId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>SMRTMS.Event_Attendees.User_ID</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>SMRTMS.Event_Attendees.Event_ID</code>.
	 */
	public void setEventId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>SMRTMS.Event_Attendees.Event_ID</code>.
	 */
	public Integer getEventId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return EventAttendees.EVENT_ATTENDEES.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return EventAttendees.EVENT_ATTENDEES.EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventAttendeesRecord value1(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventAttendeesRecord value2(Integer value) {
		setEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventAttendeesRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventAttendeesRecord
	 */
	public EventAttendeesRecord() {
		super(EventAttendees.EVENT_ATTENDEES);
	}

	/**
	 * Create a detached, initialised EventAttendeesRecord
	 */
	public EventAttendeesRecord(Integer userId, Integer eventId) {
		super(EventAttendees.EVENT_ATTENDEES);

		setValue(0, userId);
		setValue(1, eventId);
	}
}
