/**
 * This class is generated by jOOQ
 */
package jooqdb.tables.records;


import javax.annotation.Generated;

import jooqdb.tables.Event;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRecord extends UpdatableRecordImpl<EventRecord> implements Record6<Integer, String, String, Double, Double, Integer> {

	private static final long serialVersionUID = -1989347301;

	/**
	 * Setter for <code>SMRTMS.Event.ID</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>SMRTMS.Event.ID</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>SMRTMS.Event.Name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>SMRTMS.Event.Name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>SMRTMS.Event.Description</code>.
	 */
	public void setDescription(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>SMRTMS.Event.Description</code>.
	 */
	public String getDescription() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>SMRTMS.Event.Longitude</code>.
	 */
	public void setLongitude(Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>SMRTMS.Event.Longitude</code>.
	 */
	public Double getLongitude() {
		return (Double) getValue(3);
	}

	/**
	 * Setter for <code>SMRTMS.Event.Latitude</code>.
	 */
	public void setLatitude(Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>SMRTMS.Event.Latitude</code>.
	 */
	public Double getLatitude() {
		return (Double) getValue(4);
	}

	/**
	 * Setter for <code>SMRTMS.Event.Attendees</code>.
	 */
	public void setAttendees(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>SMRTMS.Event.Attendees</code>.
	 */
	public Integer getAttendees() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, Double, Double, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, Double, Double, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Event.EVENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Event.EVENT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Event.EVENT.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field4() {
		return Event.EVENT.LONGITUDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field5() {
		return Event.EVENT.LATITUDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Event.EVENT.ATTENDEES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value4() {
		return getLongitude();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value5() {
		return getLatitude();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getAttendees();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value3(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value4(Double value) {
		setLongitude(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value5(Double value) {
		setLatitude(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value6(Integer value) {
		setAttendees(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord values(Integer value1, String value2, String value3, Double value4, Double value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventRecord
	 */
	public EventRecord() {
		super(Event.EVENT);
	}

	/**
	 * Create a detached, initialised EventRecord
	 */
	public EventRecord(Integer id, String name, String description, Double longitude, Double latitude, Integer attendees) {
		super(Event.EVENT);

		setValue(0, id);
		setValue(1, name);
		setValue(2, description);
		setValue(3, longitude);
		setValue(4, latitude);
		setValue(5, attendees);
	}
}
